image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y
  - dotnet restore src/TCode.r2rml4net.sln

before_build:
  - ps: gitversion /l console /output buildserver /updateassemblyinfo

build_script:
  - ps: dotnet pack -c Release -o $env:APPVEYOR_BUILD_FOLDER/nugets src/TCode.r2rml4net /p:Version=$env:GitVersion_LegacySemVerPadded

test_script:
  - ps: Get-ChildItem -R -File -Filter '*Tests.csproj' | % {
          Push-Location $_.Directory
          dotnet xunit
          if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
          Pop-Location
        }

artifacts:
  - path: 'nugets\*.nupkg'
